### ISSUE TITLE
Readme: 10 meetings summary just shows 2 (and some more improvements)

### ISSUE THREAD

**Issue by Daniel-at-git** [manishkatyan/bbb-events#2]
In Readme.md 

# pass the most recent 10 meetings to get their summary
ls -ltr /var/bigbluebutton/recording/raw/ | tail -n 2 | awk '{print $9}' | xargs  -l ./meeting_analytics.sh

just shows 2 meetings.

Any you can also skip awk if you do it like this
ls -1tr /var/bigbluebutton/recording/raw/ | tail -n 10 | xargs  -l ./meeting_analytics.sh

**Comment by arun-hel** [comment]
Issue fixed with #3
